FROM php:8.1-apache

RUN apt-get update && apt-get install -y \
	libmariadb-dev \
	&& docker-php-ext-install mysqli \
	&& docker-php-ext-enable mysqli \
	&& apt-get clean

COPY app/. /var/www/html

WORKDIR /var/www/html

EXPOSE 8080
