version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    # command: [ "sh", "-c", "php artisan migrate:fresh && php artisan test" ]
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_DATABASE=vt
      - DB_USERNAME=vt_user
      - DB_PASSWORD=777
    volumes:
      - "./app:/var/www/html"
    ports:
      - "81:80"

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=vt
      - MYSQL_USER=vt_user
      - MYSQL_PASSWORD=777
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - "3310:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u ruslan" ]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8002:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
